name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup GCP Credentials
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > Deployment/terraform/creds.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.3.0'
        terraform_wrapper: false 
        
    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install packer

    - name: Validate and Build Image with Packer
      run: |
        packer init Deployment/packer.pkr.hcl
        packer build Deployment/packer.pkr.hcl
        
    - name: Initialize Terraform
      run: |
        cd Deployment/terraform
        export GOOGLE_CREDENTIALS="${{ secrets.GCP_BASE64 }}"
        terraform init

    - name: Apply Terraform
      run: |
        cd Deployment/terraform 
        export GOOGLE_CREDENTIALS="${{ secrets.GCP_BASE64 }}"
        terraform apply --auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_BASE64 }}